spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: devuser
    password: devpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

example:
  profile-specific-property: "This is a dev property"
